### PR TITLE
fix(init.js): silently handles exceptions thrown by child_process

### LINKED ISSUE #27: Unhandled child_process exception: init.js
Line 11 throws an exception if `.gitconfig` has no `github.username` field, therefore line 12 never runs (or the rest of the program for that matter).

https://github.com/osdevisnot/klap/blob/2e9cc51f9d92cd9065f7aea1e216eeefe3fce839/src/init.js#L10-L15

### PR DESCRIPTION
**Pull request by dnl-brnr**
If a user doesn't have a github.user field in their .gitconfig, `klap init` will currently throw an exception and halt. The fallback of `user.name` is not reached in any case. This commit addresses the issue by adding `try...catch` blocks to silently catch the exceptions.

It also omits adding the undefined properties to `package.json` in favor of letting the author handle them manually, meaning, no `author` field will be generated by klap.

There may be a better way to handle this, such as alerting the user (since they might like to know if they don't have a properly configured .gitconfig), but I'll leave that up to you! 👏

fix #27

### CODE REVIEW

File: src/init.js [hunk 1]
```diff
@@ -8,9 +8,21 @@ import { exec, exists, read, write } from './utils';
...
+  } catch {
+    try {
+      user = exec('git config user.name');
+    } catch {
+      // neither github.username or user.name exist
+    }
+  }
+  try {
+    email = exec('git config user.email');
+  } catch {
```
Comment (osdevisnot) [inline src/init.js]: I thought I had this covered in `exec` function in utils.js.
Can we move the try catch there to avoid multiple try catch blocks here?
Maybe return false when exec fails?

File: src/init.js [hunk 2]
```diff
@@ -22,10 +34,12 @@ const writePackage = async (template, { user, email }) => {
...
-  pkg = merge(
-    { repository: `${user}/${pkg.name}`, author: `${user} <${email}>` },
-    pkg
-  );
+  // only add fields to pkg if defined, otherwise omit them for author to
+  // handle manually
+  if (user) {
+    pkg = merge({ repository: `${user}/${pkg.name}` }, pkg);
+    if (email) pkg = merge({ author: `${user} <${email}>` }, pkg);
+  }
```
Comment (osdevisnot) [inline src/init.js]: We should probably emit a warning here to let author know to handle these two fields manually?

Comment (dnl-brnr) [reply src/init.js]: I think it's a good idea. Maybe something like: 


"Could not source user info from `.gitconfig`. `repository` and `author` fields NOT added to `package.json`. Please add them manually _or_ add `user.email` and `github.user` to `.gitconfig` and re-run `klap init`"

Or if that's too long, maybe just:

"`repository` and `author` fields NOT added to `package.json`. Please add them manually.

Comment (osdevisnot) [reply src/init.js]: Yeah short is better I guess.

File: src/init.js (hunk 1 above)
Comment (dnl-brnr) [reply src/init.js]: Should be handled by https://github.com/osdevisnot/klap/pull/28/commits/6729494dd47f4bd85880e51647cc802a7c7c68d8

**Comment by osdevisnot** [comment]
@all-contributors please add @dnl-brnr for code
